optimizer:
  type: AdamW
  kwargs:
    lr: 5e-5
    weight_decay: 0.05

scheduler:
  type: CosLR
  kwargs:
    epochs: 100
    initial_epochs: 5

dataset:
  train:
    _base_: ReConV2/cfgs/dataset_configs/Scaffold.yaml
    others:
      subset: train
      with_color: False
  val:
    _base_: ReConV2/cfgs/dataset_configs/Scaffold.yaml
    others:
      subset: val
      with_color: False
  test:
    _base_: ReConV2/cfgs/dataset_configs/Scaffold.yaml
    others:
      subset: test
      with_color: False

model:
  NAME: PointTransformer
  embed_dim: 768
  depth: 12
  drop_path_rate: 0.2
  cls_dim: 16
  num_heads: 12
  group_size: 32
  num_group: 64
  with_color: False
  large_embedding: True
  img_queries: 13
  text_queries: 3
  decoder_depth: 4

npoints: 8192
total_bs: 16
step_per_update: 2
max_epoch: 100
grad_norm_clip: 10
